# Generated by Django 6.0.3 on 2026-03-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='docente', to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estudiantes', to='academico.estadoestudiante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='estudiante', to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='pensum',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pensum', to='academico.curso'),
        ),
        migrations.AddField(
            model_name='pensum',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pensum', to='academico.grado'),
        ),
        migrations.AlterUniqueTogether(
            name='pensum',
            unique_together={('grado', 'curso')},
        ),
    ]
