# Generated by Django 6.0.3 on 2026-03-27 07:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('es_mejoramiento', models.BooleanField(default=False)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripciones.asignacioncurso')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='inscripciones.inscripcion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizacion.unidad')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_mejoramiento', False)), fields=('inscripcion', 'asignacion', 'unidad'), name='uq_nota_ordinaria'), models.UniqueConstraint(condition=models.Q(('es_mejoramiento', True)), fields=('inscripcion', 'asignacion', 'unidad'), name='uq_nota_mejoramiento')],
            },
        ),
        migrations.CreateModel(
            name='NotaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aprobado', models.BooleanField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripciones.asignacioncurso')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion')),
            ],
            options={
                'unique_together': {('inscripcion', 'asignacion')},
            },
        ),
        migrations.CreateModel(
            name='Recuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_recuperacion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aprobado', models.BooleanField()),
                ('fecha_examen', models.DateField()),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripciones.asignacioncurso')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion')),
            ],
            options={
                'unique_together': {('inscripcion', 'asignacion')},
            },
        ),
    ]
