# Generated by Django 6.0.3 on 2026-05-07 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notas', to='inscripciones.inscripcion'),
        ),
        migrations.AlterField(
            model_name='notafinal',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripciones.inscripcion'),
        ),
        migrations.AlterField(
            model_name='recuperacion',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripciones.inscripcion'),
        ),
    ]
