# Generated by Django 6.0.3 on 2026-03-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='chk_ciclo_fechas')],
            },
        ),
        migrations.CreateModel(
            name='GradoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizacion.cicloescolar')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.grado')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.seccion')),
            ],
            options={
                'unique_together': {('grado', 'seccion', 'ciclo')},
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='organizacion.cicloescolar')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('numero__gte', 1), ('numero__lte', 6)), name='chk_unidad_numero'), models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='chk_unidad_fechas')],
                'unique_together': {('ciclo', 'numero')},
            },
        ),
    ]
