# Generated by Django 6.0.3 on 2026-03-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.docente')),
                ('grado_seccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizacion.gradoseccion')),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.pensum')),
            ],
            options={
                'unique_together': {('pensum', 'grado_seccion')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(blank=True, max_length=30, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='inscripciones.asignacioncurso')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inscripciones', to='academico.estudiante')),
                ('grado_seccion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inscripciones', to='organizacion.gradoseccion')),
            ],
            options={
                'unique_together': {('estudiante', 'grado_seccion')},
            },
        ),
    ]
